# Custom Command Toggle 
# Exported settings for the Custom Command Toggle extension 
# File generated on 8/1/2026, 12:06:10 PM 
# 
# --- Settings Information ---
# button-name: <text> 
# icon: <text> 
# toggle-on-command: <command> 
# toggle-off-command: <command> 
# check-status-command: <command> 
# search-term: <text> 
# initial-state: 0, 1, 2, or 3 
#     0 = On 
#     1 = Off 
#     2 = Previous state 
#     3 = Command output 
# run-at-startup: true or false 
# startup-delay-time: 0-10 (seconds) 
# check-status-delay-time: 0-10 (seconds) 
# button-click-action: 0, 1, or 2 
#     0 = Always on 
#     1 = Always off 
#     2 = Toggle 
# check-exit-code: true or false 
# show-indicator: true or false 
# close-menu: true or false 
# command-sync: true or false 
# polling-frequency: 2-900 (seconds) 
# keyboard-shortcut: <shortcut> 
# enabled: true or false 
# 
#
[Toggle 1]
button-name=Silent Fan
icon=weather-windy-symbolic
toggle-on-command=sudo nbfc config --set "HP ENVY x360 2-in-1 Laptop 15-fh0xxx (Silent)" && sudo nbfc restart
toggle-off-command=sudo nbfc config --set "HP ENVY x360 2-in-1 Laptop 15-fh0xxx (Default)" && sudo nbfc restart
check-status-command=nbfc status
search-term=Silent
initial-state=3
run-at-startup=false
startup-delay-time=3
check-status-delay-time=3
button-click-action=2
check-exit-code=false
show-indicator=true
close-menu=false
command-sync=false
polling-frequency=10
keyboard-shortcut=
enabled=true

[Toggle 2]
button-name=CPU Turbo
icon=uninterruptible-power-supply-symbolic
toggle-on-command=sudo systemctl stop cpu-noturbo
toggle-off-command=sudo systemctl start cpu-noturbo
check-status-command=cat /sys/devices/system/cpu/cpufreq/boost
search-term=1
initial-state=3
run-at-startup=false
startup-delay-time=3
check-status-delay-time=3
button-click-action=2
check-exit-code=false
show-indicator=true
close-menu=false
command-sync=false
polling-frequency=10
keyboard-shortcut=
enabled=true

[Toggle 3]
button-name=Screensaver
icon=preferences-desktop-screensaver-symbolic
toggle-on-command=systemctl --user start screensaver.service
toggle-off-command=systemctl --user stop screensaver.service
check-status-command=systemctl --user status screensaver.service
search-term=active (running)
initial-state=3
run-at-startup=false
startup-delay-time=3
check-status-delay-time=3
button-click-action=2
check-exit-code=false
show-indicator=true
close-menu=false
command-sync=false
polling-frequency=10
keyboard-shortcut=
enabled=true
